In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
#0-d arrays/scalars
import numpy as np
arr=np.array(42)
print(arr)

42


In [3]:
#1-d arrays
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
#an array that has 1-d arrray as its elements is called as 2-d array. they often represent a matrix
#2-d arrays containing 2 arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#3-d array with 2 2-d arrays in it
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
#numpy arrays provides the ndim attribute tht returns and integer tht tells us how many dimensions the arrays have
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5,6])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,4],[5,6,7]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
#accesing array elements
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [17]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0]+arr[3])

5


In [22]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [23]:
#slice element from index 1 to index 5 from following arrays
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:5])

[1 2 3 4 5]


In [25]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [26]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [27]:
#negative slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [30]:
#step:skips a digit
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [29]:
#step 
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
