In [7]:
#create a 3x3 numpy array of all true
import numpy as np

arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
#reverse a 1d numpy array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)


[5 4 3 2 1]


In [9]:
#create a 3x3 identity matrix
import numpy as np

identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#convert a python list into numpy list
import numpy as np

my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)

print(arr)


[1 2 3 4 5]


In [11]:
#perform arithmetic operation on two numpy arrays element wise
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Addition
print(a - b)  # Subtraction
print(a * b)  # Multiplication
print(a / b)  # Division


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
