In [1]:
#slicing 2-d array
#slicing a 2d array involves specifying ranges for both the rows and columns,seperated by a comma. the general syntax is array
#[row_start:row_stop:row_step,col_star:col_stop:col_step]
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
element=arr[1,2]
print(element)

6


In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
row_slice=arr[0:2, :]
print(row_slice)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
col_slice=arr[:,1:3]
print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
